
logLevel = "<%= p("traefik.log_level") %>"

[consulCatalog]
endpoint = "consul.service.consul:8500"

defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/var/vcap/jobs/traefik/config/ssl/tls.crt"
      KeyFile = "/var/vcap/jobs/traefik/config/ssl/tls.key"
