logLevel = "<%= p("traefik.log_level") %>"

[consulCatalog]
endpoint = "consul.service.consul:8500"

defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/var/vcap/jobs/traefik/config/ssl/tls.crt"
      KeyFile = "/var/vcap/jobs/traefik/config/ssl/tls.key"

  [entryPoints.admin]
  address = ":8080"
  [entryPoints.admin.auth.basic]
  users = [<% p('traefik.admin.users').each do |u| %><%="\"#{u}\""%>,<% end %>]
    [entryPoints.admin.tls]
      [[entryPoints.admin.tls.certificates]]
      CertFile = "/var/vcap/jobs/traefik/config/ssl/tls.crt"
      KeyFile = "/var/vcap/jobs/traefik/config/ssl/tls.key"


[web]
address = "127.0.0.1:3000"
path = "/traefik"

[file]

[frontends]
  [frontends.traefik]
  backend = "traefik"
  entrypoints = ["admin"]
    [frontends.traefik.routes.traefik]
    rule = "PathPrefix:/traefik"

[backends]
  [backends.traefik]
    [backends.traefik.servers.local]
    url = "http://127.0.0.1:3000"
