logLevel = "<%= p("traefik.log_level") %>"
defaultEntryPoints = ["http","https"]

[consulCatalog]
endpoint = "<%= p('traefik.consul_addr') %>"
watch = true
constraints = ["tag==enabled"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/var/vcap/jobs/traefik/config/ssl/tls.crt"
      KeyFile = "/var/vcap/jobs/traefik/config/ssl/tls.key"

  [entryPoints.admin]
  address = ":8443"
  [entryPoints.admin.auth.basic]
  users = [<% p('traefik.admin.users').each do |u| %><%="\"#{u}\""%>,<% end %>]
    [entryPoints.admin.tls]
      [[entryPoints.admin.tls.certificates]]
      CertFile = "/var/vcap/jobs/traefik/config/ssl/tls.crt"
      KeyFile = "/var/vcap/jobs/traefik/config/ssl/tls.key"


[web]
address = "127.0.0.1:3000"

[file]

[frontends]
  [frontends.traefik]
  backend = "traefik"
  entrypoints = ["admin"]
  [frontends.consul]
  backend = "consul"
  entrypoints = ["admin"]
    [frontends.consul.routes.consul]
    rule = "HostRegexp: consul.{domain:.*}"

[backends]
  [backends.traefik]
    [backends.traefik.servers.local]
    url = "http://127.0.0.1:3000"
  [backends.consul]
    [backends.consul.servers.local]
    url = "<%= p('traefik.consul_addr') %>"
