meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: server
    templates:
    - name: consul
      release: consul
      provides:
        consul_servers: { as: consul_leaders }
      consumes:
          consul_servers: { from: consul_leaders }
    - name: nomad-server
      release: nomad
    - name: hashi-ui
      release: nomad
    instances: 1
    persistent_disk: 3200
    resource_pool: small_z1
    networks: (( param "please set server networks" ))
    properties:
      consul:
        server: true

  - name: node
    templates:
    - name: docker
      release: docker
    - name: consul
      release: consul
      consumes:
        consul_servers: { from: consul_leaders }
    - name: nomad-client
      release: nomad
    instances: 1
    persistent_disk: 3200
    resource_pool: small_z1
    networks: (( param "please set node networks" ))
    properties:
      consul:
        server: false

networks: (( param "please set networks" ))

properties:
  nomad:
    leave_on_terminate: true
